ImpressCMS/impresscms

- htdocs/libraries/jquery/helptip.js
Lines 20 & 22.
Change: "attr("checked",true)" to "prop("checked",true)" and
"attr("checked",false)" to "prop("checked",false)"
Reason: jQuery 1.6 needs to use 'prop()' function.
> Fix Ticket #881.

- htdocs/libraries/icms/properties/Handler.php
Few small bugfixes for code used to clean values for DTYPE_OBJECT for properties.
This is also needed to pass one of new PHP Unit tests.
> Bug fix for object data type in properties

- htdocs/composer.json
- htdocs/modules/system/class/AvatarsHandler.php
- htdocs/modules/system/class/CommentsHandler.php
- htdocs/modules/system/class/GroupsHandler.php
- htdocs/modules/system/class/ImagesHandler.php
- htdocs/modules/system/class/ModulesHandler.php
- htdocs/modules/system/class/TplsetsHandler.php
- htdocs/modules/system/class/Userrank.php
- htdocs/modules/system/class/UserrankHandler.php
- htdocs/modules/system/class/UsersHandler.php
Classes reverted to have standard declarations instead of class_aliases, so composer can properly add them to its autoloader. 
Also - the icms library is PSR-0 compliant, so we can define that in composer.json
Ref #915
> Adjustments for the composer autoload and class_alias - #915

- README.md
Added icon with latest release number and license now autodetected for icon from repo (if we change our license, we just need to update License.txt file with new one... at least for readme.md)
> Icons in readme.md improvements

- htdocs/libraries/icms/core/DataFilter.php
(noticed at the top of every page - buildRelevantUrls was the calling function)
test #920
> Fixes warning with invalid index 'options'

- htdocs/libraries/icms/ipf/view/Table.php
The function input variable (fct) was being stripped by the new filtering added in 1.3.10. Added it here. This addresses the pagination issue
There appears to be some whitespace changes in this too - not too many though!
> Adding admin function to allowed input variables test #102

- htdocs/index.php
Currently, if the Registered Users group has a default module/page set, it is ignored if the user is a member of another group that has no default module/page set.
Perhaps the Registered Users group should be used as a failsafe, so that you don't have to set default pages for every single group in your site? The only downside I can see is that perhaps webmasters would have specifically set a certain group to have no default page and intend that as the behaviour for that group. I think it's more powerful to rely on Registered Users to avoid people having to set a default page for every group though. Especially on sites with many many groups.
> Use reg users group if no default module/page set

- htdocs/composer.json
So I have listed all PHp extensions in composer.json that required to run our CMS.
> Added required PHP extensions in composer.json

- htdocs/composer.json
I don't know where this is used but at least when running `composer validate` we got warning:
> License "GPLv2" is not a valid SPDX license identifier, see https://spdx.org/licenses/ if you use an open license.
> If the software is closed-source, you may use "proprietary" as license.
So, this change should fix such issue. 
I'm not sure if this better `GPL-2.0-only` or `GPL-2.0-or-later` so take a look.
> SPDX license in composer.json fix

- htdocs/composer.json
In previous pull request I have added some PHP extensions in required list, however some of them are optional.
> A bit more improved listing php extensions in composer.json

- htdocs/libraries/icms/form/elements/Editor.php
- htdocs/libraries/icms/form/elements/Hiddentoken.php
Some form elements has old constructors that will not work on never PHP versions. This pull request fixes.
> Deprecated constructors for form elements fixes

- htdocs/libraries/icms/form/Base.php
Because we ipf base form inherits base xoops form, we have access level problem. $_elements field was set to private. So, this is fix for such issue.
> Changed $_elements var access level in libraries/icms/form/Base.php

- htdocs/libraries/icms/member/Handler.php
IPF member class is delivered from member class and that's why it has problem with private $_uHandler var. This small pull request should fix this issue.
> Fixed bug with $_uHandler var access level for ipf member class

- htdocs/include/constants.php
I think we could remove some XOOPS_* constants definitions from our core, because we don't use them anymore (maybe there are some modules that uses but I don't think so that would be a major issue).
> Remove XOOPS_* paths constants definitions from constants.php

- htdocs/include/functions.php
- htdocs/libraries/icms/core/DataFilter.php
- htdocs/plugins/textsanitizer/hashtags/hashtags.php
- htdocs/plugins/textsanitizer/mentions/mentions.php
- htdocs/plugins/textsanitizer/syntaxhighlightcss/syntaxhighlightcss.php
- htdocs/plugins/textsanitizer/syntaxhighlighthtml/syntaxhighlighthtml.php
- htdocs/plugins/textsanitizer/syntaxhighlightjs/syntaxhighlightjs.php
- htdocs/plugins/textsanitizer/syntaxhighlightphp/syntaxhighlightphp.php
- htdocs/plugins/textsanitizer/wiki/wiki.php
- htdocs/plugins/textsanitizer/youtube/youtube.php
e modifier was DEPRECATED in PHP 5.5.0, and REMOVED as of PHP 7.0.0. So, this pull requests fixes most of never PHP issues (f.e. all custom blocks on PHP 7.0 are rendered as empty without this fix).
One issue with this plugin is that it doesn't improve `icms_cleanTags` method. There are too much magic. But because it's market as needs to be removed, I think everything would be good enough.
> Remove preg_replace e modifier from core

- htdocs/composer.json
- htdocs/libraries/icms/core/Versionchecker.php
- htdocs/modules/system/admin/version.php
- htdocs/modules/system/language/english/admin/version.php
- htdocs/modules/system/templates/admin/system_adm_version.html
- htdocs/themes/core/modules/system/admin/system_adm_version.html
- tests/libraries/icms/VersionCheckerTest.php
We can get latest version info from GitHub so why not to use this data when checking for updates? This pull requests does that!
One possible issue with this change is that it doesn't checks for anything on GitHub that is not a final release but I think maybe that is not a bad thing.
> Version checker uses GitHub for checking updates

- tests/libraries/icms/SessionTest.php
Previously SessionTest.php had class SecurityTest but same class existed also in SecurityTest.php, so this pull request should fix such issue.
> Fixed class name for SessionTest.php

- libraries/icms/module/Handler.php
Newer PHP needs that inherinted classes methods should have same args. This fixes such issues for icms_module_Handler.
> Fixed 'Declaration of x must be compatible with y' issues for icms_module_Handler

- .editorconfig
This should make use same spaces length in all json, yml and yaml files not only `package.json` and `.travis.yml`, because we right now have a bit more files with such extensions.
> Same ident style for all json, yml and yaml files

- modules/system/blocks/system_admin_blocks.php
We don't have /upgrade/ folder so we don't need such warning
> Removed /upgrade/ folder warning in system module

- libraries/phpmailer/index.html
- libraries/phpmailer/language/index.html
Similar to #250 but for phpmailer index.html files in libraries folder. We don't need them anymore.
> Removed some existing index.html files for phpmailer in libraries folder

- htdocs/install/modulesadmin.php
- libraries/icms/view/Tpl.php
- modules/system/admin/modules/modules.php
- modules/system/admin/preferences.php
- modules/system/admin/tplsets.php
Calling static methods as non-static still works but it is bad thing to do. This pull request fixes such issue at least for few methods `template_touch` and `template_clear_module_cache` .
> `template_touch` and `template_clear_module_cache` now is everywhere called as static methods. 

- .scrutinizer.yml
This:
* removes some paths that where added to composer
* use same code style as .travis.yml
* disable postgresql, mongodb, redis, memcached, neo4j, rabbitmq
* PHP now 7.2.0 (not anymore 5.5)
* --enable-security-analysis
> .scrutinizer.yml now use same code style as .travis.yml + some other improvements

- htdocs/plugins/preloads/autotasks.php
> Remove var-dump from autotask preload (1.3.11)

- htdocs/install/modulesadmin.php
- include/functions.php
- libraries/icms/config/item/Object.php
- libraries/icms/member/user/Object.php
- libraries/icms/view/PageBuilder.php
- libraries/icms/view/Tpl.php
- libraries/icms/view/block/Object.php
- libraries/icms/view/theme/Object.php
- modules/system/admin/modules/modules.php
- modules/system/class/Adsense.php
- modules/system/class/Blocks.php
- modules/system/class/BlocksHandler.php
- modules/system/class/Customtag.php
- modules/system/class/Rating.php
- readpmsg.php
- userinfo.php
Because with new properties system is possible write `$obj->x` instead of `$obj->getVar('x', 'n')`, this pull request uses this new feature and a bit improved code syntax style.
> Coding style improvement: `$obj->getVar('x', 'n')` -> `$obj->x`

- modules/system/blocks/system_admin_blocks.php
CSSTidy is loaded with composer so we don't need such warning (such detection it will not work)
> Remove CSSTidy vulnerability warning

- .scrutinizer.yml
Adding spaces around the operators
#293
> Changing coding style in scrutinizer config for ternary operators fix

- htdocs/libraries/icms/plugins/EditorHandler.php
Path was missing a directory separator and the control was being called
more than once on the same page, making the include_once call not return
what was needed. Thanks, @mekdrop
I'm not sure where the line endings got altered...
> Corrected path for editors cache file and include logic See #305

- htdocs/modules/system/admin/modulesadmin/modulesadmin.php
> version number is not shown for uninstalled modules

- htdocs/libraries/icms/core/DataFilter.php
fix #361
the code tags were not being preserved, so the final result was just base64 encoded. The css style for the div had extra characters in it, so it did not render properly.
> Adjusting code tag processing to accurately handle pre-existing content

- htdocs/libraries/icms/member/groupperm/Handler.php
Fix PHP Strict error : Strict: Accessing static property icms_member_groupperm_Handler::$_cachedRights as non static in file /libraries/icms/member/groupperm/Handler.php line 390
the $_cachedRights variable was not static
> Update Group permission Handler.php for strict PHP

- .codeclimate.yml
Camelcase is not in our code style guide.
> disabled the camelcase check

- htdocs/robots.txt
There was some disallows that for 2.x structure doesn't make sense in robots.txt file. So, removed.
> removed many unused now disallows from robots.txt file

- htdocs/modules/system/include/update.php
while removing the install ping (that didn't work due to no server at the receiving end) the version update was removed as well. That is now restored.
> successful upgrading now updates version info

- htdocs/libraries/icms/member/groupperm/Handler.php
The change to comply with strict mode was incomplete - I missed the property indicator '$'. This adds that and the install continues successfully on PHP 5.6
> Correcting static property reference. Fix #472

- htdocs/libraries/icms/core/Object.php
replace continue in icms_core_Object with break. Fix #477
> PHP7 Fix to replace continue with break in cleanvar

- htdocs/install/page_modcheck.php
> check mysql using PDO now

- htdocs/footer.php
Believe it or not, but Chrome didn't like the date to be too far in the past. Now the login works as expected in Chrome and the Chromium-based Edge.
Fix #100
> make expiration header dynamic in the past

- htdocs/libraries/icms/image/Handler.php
getObjects and getList generated compatibility warnings because signatures from parent classes were so different. This pull request fixes this small problem.
> Fixed function signatures in icms_image_Handler (1.4)

- htdocs/libraries/icms/view/theme/Factory.php
Just a small code improvement.
> Fixed suppressed warning if variable $options['folderName'] is undefined or empty when creating theme (1.4.x)

- libraries/icms/view/theme/Factory.php
Sometimes is possible to get warning if $options['folderName'] in view/theme/factory -> createInstance is undefined.
> Fixed bug for possible warning that $options['folderName'] is undefined (2.0.x)

- libraries/icms/image/Handler.php
getObjects and getList generated compatibility warnings because signatures from parent classes were so different. This pull request fixes this small problem.
> Fixed function signatures in icms_image_Handler (2.0)

- htdocs/install/page_pathsettings.php
PathStuffController (for installer) used old style constructor. This fixes such issue.
> Fixed PathStuffController's constructor

- .github/workflows/stale.yml
Every two months all pull requests and issues will be automatically rechecked and if they are very old marked as stale.  If this will work as expected, I think this will be a good indicator what haven't changed and must be looked into.
> Added 'stale' github action

- libraries/wideimage/index.html
- libraries/wideimage/lib/Font/index.html
- libraries/wideimage/lib/Mapper/index.html
- libraries/wideimage/lib/Operation/index.html
- libraries/wideimage/lib/index.html
- libraries/wideimage/lib/vendor/JPEXS/index.html
- libraries/wideimage/lib/vendor/de77/index.html
- libraries/wideimage/lib/vendor/index.html
Somehow some wideimage index.html files where left in repo. This pull request is removing them.
> Removing wideimage directories and files

- include/constants.php
We don't have build in XML classes anymore. So, we don't need to have such check.
> Remove XOOPS_XMLRPC check from constants file

- libraries/icms/db/Connection.php
I plan to add whoops (like laravel use) for error handling. And it is very sensible for all exceptions (DEPRECTATED also included), so this commit removes such `trigger_error` functions from database code and replaced with comments.
> Deprecated warnings made into @deprecated comments in database connection class

- htdocs/install/install_tpl.php
- htdocs/install/page_dbsettings.php
Prototype was interfering with pathsettings.js. Since prototype is only needed on the dbsettings page, moving there to resolve this and not break #529
> Move prototype inclusion so trust_path creation works fixes #569

- htdocs/install/makedata.php
Resolves #81
New installations use core theme that uses bootstrap however there is no much done for old installations because some users could prefer older iTheme and I think it would be bad to force them change that.
> core theme as default

- htdocs/install/sql/mysql.structure.sql
Fixes #576
Quotes (back-ticks) have been added around all column names and indexes to prevent conflicts with new reserved words.
> Adding quotes around column and index names for MySQL 8 compatibility.

- libraries/icms.php
Simple fix for removing one of notices messages.
> Fixes 'Notice: Only variables should be passed by reference in file /libraries/icms.php line 195'

- README.md
- tests/libraries/icms/ViewTest.php
Fixed tests that were broken due methods that were removed because of deprecation.
Also, removed tests results badge from 'readme' file because it showed always correct results but not always that was a case. I think this status can be seen 
at top of branch last commit ![image](https://user-images.githubusercontent.com/342641/72764071-290a8800-3bef-11ea-866f-461850b8872b.png) so I don't see any big reason to have this one also in readme, that's why I removed.
> Fix tests and removes tests result badge

- .github/workflows/test.yml
Only master branch has tests, so running tests from other release branches removed.
Also, tests will now run only if changes includes *.php or/and *.js or changed test workflow file.
> Run tests only for master branch and if new commits has correct extensions

- htdocs/modules/system/admin/modulesadmin/modulesadmin.php
Adding a definition of the path to the sql file when not using PDO. I know PDO is the recommended db connection, it is not a requirement for this version, though.
Closes #607
> Fix module install sql path

- htdocs/modules/system/icms_version.php
This takes care of the missing menu on top of ACP module pages. 
Fix #604
> add system_adm_modulemenu.html to icms_Version

- htdocs/modules/system/templates/system_userform.html
no longer using the xoops_redirect, but the icms_requesturi variable fixes the issue with the blank redirect.
Fixes the issue, instead of my previous PR.
> Fix blank page after login

- core/Database/Criteria/CriteriaItem.php
> Fixes bug when if value in criteria is not a string some comparisons fails

- composer.json
- htdocs/index.php
Previously in index.php internal HTTp error codes where not correctly detected, this pull request should fix that.
> When handling HTTP errors index.php now correctly detects status code

- .github/workflows/test.yml
- composer.json
- core/SetupSteps/Module/Install/CacheClearSetupStep.php
- core/SetupSteps/Module/Uninstall/CacheClearSetupStep.php
- core/SetupSteps/Module/Update/CacheClearSetupStep.php
- libraries/icms.php
- modules/system/language/english/admin/modules.php
Adds a step that clears cache when installing, uninstalling or updating module, so when routes, services, providers will be rebuild also depending module actions (previously user needed to delete cache to see differences manually).
> Clears cache when installing, uninstalling or updating module

- composer.json
- composer.lock
It seems we incorrectly said in our composer.json that we use GPLv2.0 only license but in reality our code is based on GPLv2.0 or later license (I have checked differences in our code base + all Xoops inherited file headers).
> Fixes license in composer.json

- composer.json
- composer.lock
- core/Controllers/LegacyController.php
- core/Extensions/ComposerDefinitions/RoutesComposerDefinition.php
- htdocs/index.php
From now if ImpressCMS is installed in subfolder and moved to other folder, no cache regeneration would be needed.
Also, this probably would fix #785
> Changed way how paths in subfolder would be handled

- htdocs/libraries/icms/ipf/Controller.php
Fixes possibility to use relative filenames as POST values for deleting some content via IPFController.
This was found after investingating https://hackerone.com/reports/1035311 by siva teja (siva12)
Idk why all file was marked as changed. Changes were only on lines 54 and 102.
> Prevents using submitted filenames with ../ for controller

- .github/workflows/test.yml
Because we still can't use composer 2.0 due mindplay-dk/composer-locator#8 issue at least for a while we still require to use composer 1.0 for 2.0 installations.
> Temp fix: use composer v1.0 for tests

- .whitesource
Whitesource tries to scan .js files in composer packages installations and I didn't find any info how to prevent that, so I have decided to remove it.
We use Dependabot and HackerOne. These services I think could replace the need for Whitesource.
> Remove whitesource config

- htdocs/index.php
Accedently I found that such bug exists. For such installations user will get fatal error on any page.
> Fixed null response bug for root path instalations

- .github/workflows/test.yml
We do not really need that code climate steps would succeed to make sure that everything ok - these steps just uploads tests results to codeclimate. So, I made them as optional.
> Code Climate steps are now not required in GitLabCI test action

- core/Extensions/ComposerDefinitions/RoutesComposerDefinition.php
It seems a missing '\\' for strategy service names was a problem. So here is a fix.
> Fixed bug when was not possible to automatically resolve correct Route Strategy service due missing escape character in beginning

- .github/release-drafter.yml
I'm not sure 100% but from documentation it seems this could fix issue when 1.4.x and 2.x are losing changes when regenerating new changelog.
> Added filter-by-commitish option in release drafter config

- .github/dependabot.yml
GitHub is integrating dependabot and will remove dependabot website in near future, so to keep using this amazing service and to have some new cool features new configuration file is needed.
> Added dependabot v2 config

- .github/release-drafter.yml
> Fixed release drafter config to use correct GitHub labels when sorting tickets

- composer.json
- core/Controllers/DefaultController.php
- core/Response/ViewResponse.php
- migrations/20210104224612_add_session_extension_settings_option.php
- modules/system/language/english/admin/preferences.php
At current moment ImpressCMS doesn't automatically extends session if you leave your computer or browser tab for some time. This will helps users for such case. This could also help when you writing some big documents.  From now sessions are extended automatically by periodically pinging server with ajax requests.
In future I think it would be cool it could work with websockets too - but at current moment I think it would be good enough for us.
> Added ping to extend sessions automatically

- composer.json
- core/Extensions/Smarty/Blocks/TransBlock.php
- core/Extensions/Smarty/Modifiers/TransVarModifier.php
- core/Extensions/Smarty/SmartyBlockExtensionInterface.php
- core/Extensions/Smarty/SmartyModifierExtensionInterface.php
- core/Providers/TranslatorServiceProvider.php
- core/View/Template.php
Previously added #801 wasn't accesible from templates. This pull request adds needed for that functionality.
There are two new ways to translate strings in template: function blocks and vars modifiers.
F.e. if I want to translate `_AD_INSTALLEDMODULES` that exists in admin.php I could write it...
....with block function:
```
<{trans domain='admin'}>_AD_INSTALLEDMODULES<{/trans}>
```
...with var modifier:
```
<{"_AD_INSTALLEDMODULES"|trans:[]:'admin'}>
```
Block function supports such attributes:
| Atribute | What it does? | Default value |
|----------|-----------------|----------------|
| parameters | Key/value lists that should be replaced in translated string |  [] |
| domain | Domain from where to get translation string (in most cases same as translation file) | *(system default …
> Added smarty 'trans' block and 'trans' variable modifier for translations

- htdocs/libraries/icms/messaging/EmailHandler.php
Fixes #881 
Still for using google mail that could be noth enough - Google is moving to OAUTH and we do not have yet such functionality.
> Fix "#881 trying to send mails with SMTP auth gives missing smtp class"

- htdocs/libraries/icms/core/Logger.php
This will help easier to figure out what a blank page really means.
Example screen:
P.S.: syntax exceptions are handled >= 7.0; 5.6 handles most others; If exception happens before logger initialization also would not be handled in such way.
> Added exception handler

- htdocs/include/functions.php
Some modules like [IsengardBiz/news](https://github.com/IsengardBiz/news) has separated handlers from objects in different files. Current ICMS version prevented such file to be loaded. This should fix that.
> Fixed bug when handlers from module separate files cant be loaded

- htdocs/include/cp_functions.php
From now if that happens such module will be skipped.
> Fixed bug when admin menu can't regenerate when module folder is removed before uninstalling

- composer.json
- core/Extensions/SetupSteps/Module/Install/CacheClearSetupStep.php
- core/Extensions/SetupSteps/Module/Uninstall/CacheClearSetupStep.php
- core/Extensions/SetupSteps/Module/Update/CacheClearSetupStep.php
It seems few setup steps where not where others are, this will fix that.
> CacheClearSetup steps moved to same namespace/path as other steps

- core/View/Table/Table.php
There was bug that table component could crash if not correct order value was specified. Now it will fail silently - switching into ASC.
> Fixes crash when not correct order comes from user data for table

- include/deprecated_class_aliases.php
It seems there were few class names that were not correctly resolved for some older modules. This fixes that.
> Fixes some old class references resolving for some older modules

- core/Response/RedirectResponse.php
- include/functions.php
So from now is possible to have [PSR-7 compatible](https://www.php-fig.org/psr/psr-7/) redirect responses that works similar as redirect_header. 
This is very usefull for writing controllers actions.
> RedirectResponse now can be used for same things as redirect_header

- include/deprecated_class_aliases.php
This fixes compatibility issue for some old icms modules.
> Add IcmsPersistableController to legacy class resolving map

- composer.json
- core/Extensions/SetupSteps/Module/Install/MigrateSetupStep.php
- core/Extensions/SetupSteps/Module/Update/MigrateSetupStep.php
- phoenix.php
Previously migrations worked only for core. This adds also migrations to modules.
> Enable migrations for modules in module installer/updating/removing

- core/Extensions/SetupSteps/Module/Install/BlockSetupStep.php
- core/Extensions/SetupSteps/Module/Update/BlocksSetupStep.php
- migrations/20191230145417_add_initial_data.php
From now is possible to specify default blocks positions, weights and visibilities. 
f.e."
```yaml
"blocks": {
"1": {
"file": "system_blocks.php",
"name": "_MI_SYSTEM_BNAME2",
"description": "",
"show_func": "b_system_user_show",
"edit_func": "b_system_user_edit",
"options": "0",
"template": "system_block_user.html",
"visible": true //  this block will be made as default visible
"position": "canvas_right", // this block if available will be visible at canvas_right block position
"weight": 999 // this block will have 999 weight when sorting blocks
}
}
```
> Added posibility to specify default block weight, position and visibility

- htdocs/include/findusers.php
The token should be tied to the user session and not allow anonymous access to this form
> Accept token for valid users only

- htdocs/install/page_modulesinstall.php
Install step was looking for xoops_version instead of icms_version.
> Making sure protector gets installed during the site installation

- htdocs/install/modules/protector/trust_path/modules/protector/admin/index.php
- htdocs/libraries/icms/core/Logger.php
Allowed admin IPs was labeled incorrectly
Path disclosure for trust path in debug
> Fix for information displayed in protector admin and debug console

- core/Database/AbstractDatabaseMigration.php
- migrations/20191230123706_initialization.php
- migrations/20191230145417_add_initial_data.php
- migrations/20191230233945_setup_block_links.php
- migrations/20200125164107_update_config_for_use_with_monolog.php
- migrations/20200322181415_change_names_for_auto_task_systems_in_config.php
- migrations/20200803205508_remove_use_custom_redirection_config_option.php
- migrations/20200806213927_convert_all_textsanitizers_contents_to_h_t_m_l.php
- migrations/20200806214630_remove_settings_to_make_possible_to_use_old_style_d_h_t_m_l_editor.php
- migrations/20200807225033_remove_use_w_y_s_i_w_y_g_editor_right.php
- migrations/20200808234213_remove_mime_type_editing.php
- migrations/20200809205407_add_encrypt_cookies_settings_option.php
- migrations/20200821223712_remove_old_messangers_from_user_if_exists.php
- migrations/20200821235126_remove_open_i_d_field_from_config.php
- migrations/20210104224612_add_session_extension_settings_option.php
- phoenix.php
With this is possible to use prefix and container in all migrations without extra hacks.
> Use phoenix mini container functionality to share some custom functions between all migrations

- composer.json
Never composer needs to thrust plugins before using. This will fix that by adding required plugins to `composer.json`.
> Thrust required composer plugins

- htdocs/libraries/icms/core/DataFilter.php
- htdocs/libraries/icms/ipf/view/Table.php
Since the keys were not defined, the method was applying the default string filter.
Prevents misuse of input arrays and SQLi
> Applying the filters to inner elements of arrays

- composer.json
- composer.lock
- include/functions.php
Improves #1201
`env` function now comes from separate library `imponeer/env` to make it possible to share needed code between this and our composer plugin.
> Use imponeer/env for env function

- include/constants.php
> Fixes 'Deprecation Notice: rtrim(): Passing null to parameter #1 ($string) of type string is deprecated'

- core/Models/AbstractExtendedHandler.php
This removes the need for using this function supply translated strings.
> addPermission now uses 'caption' and 'description' as language strings

- bin/console
That is needed to remove some unnecessary tries to load non-existing language files.
> CLI console now uses English as default language

- htdocs/install/class/textsanitizer.php
Both these methods aren't very useful than were before PHP 7.0 released, so it's good time to deprecate them.
Resolves #1057 and #1056
> Deprecate addSlashes and stripSlashesGPC functions

- htdocs/libraries/icms/db/Factory.php
I accidentally found this bug. So this will fix that + some phpstorm detected issues.
> Fixes DB crash if DB encoding value is empty

- htdocs/install/makedata.php
PHP8 throws an error for undefined constants. modules/system/icms_version.php uses constants from language/<language>/global.php too
> Including necessary language file to prevent installation errors in PHP8

- htdocs/libraries/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/Core.AllowParseManyTags.txt
- htdocs/libraries/htmlpurifier/standalone/HTMLPurifier/ConfigSchema/schema/HTML.Forms.txt
Update to HTMLPurifer 4.15.0 for PHP8 compliance
> Update to HTMLPurifier for PHP8 compliance

- htdocs/header.php
- htdocs/libraries/icms/view/theme/Object.php
- htdocs/plugins/preloads/googleanalytics.php
Move the UA code to the preload. This code also looks for the value of the Google Analytics tag and decides based on that whether to add the old UA or the new GA4 script
> Move analytics code to preload

- htdocs/install/language/english/install.php
- htdocs/install/language/english/welcome.php
- htdocs/install/language/francais/welcome.php
- htdocs/install/language/italiano/welcome.php
- htdocs/install/language/nederlands/welcome.php
Some references were made in the welcome text to PHP 7.0, this now mentions a minimal requirement of PHP 7.4, and a recommendation for PHP 8.1
> Adapt install texts for PHP requirements

- htdocs/modules/system/blocks/system_blocks.php
- htdocs/modules/system/templates/blocks/system_block_themes.html
The theme selector was previously generating the HTML within the block routine, leaving very few options for themes to work with. This change updates that : the block routine in system_blocks.php now generates an array with the relevant information, and the system_block_themes.html template uses that info to create the view.
> improve theme selector

- htdocs/libraries/icms/ipf/About.php
this class still referenced $icmsModule, which no longer exists.
> replace $icmsModule with icms::$modulein about page

- htdocs/modules/system/blocks/system_blocks.php
- htdocs/modules/system/templates/blocks/system_block_multilanguage.html
This gives the themes access to the different variables of the language switcher, in order to decide on the layout. Not really backwards compatible with old themes
> language switcher refactoring

- htdocs/libraries/icms/ipf/Metagen.php
sizeof (alias of count) does not work on strings in PHP8+. When creating an IPF object, the method to generate the SEO title was using sizeof on a string, resulting in a fatal error. 
Fixes #1516
> Format code, use strlen instead of sizeof on a string

- htdocs/lostpass.php
Change in the structure of the data in the field over time has made the old partial string common for all users. This change makes it unique and temporary, basing a portion of the key on their last login. Cleaned up the email subjects a bit, too.
> Making sure password reset key is unique and temporary

- htdocs/install/sql/mysql.data.sql
- htdocs/modules/system/admin/blocksadmin/class/blocksadmin.php
- htdocs/modules/system/include/update.php
This will remove the database tables for banners and the config item  left from previous versions of the core Resolves #1528
> Remove banner tables and config item

- htdocs/libraries/icms/ipf/form/elements/Select.php
adding these brackets stops modules from bombing out saying that the function name should be a string. This is due to a [backward-incompatible change in PHP 7](https://www.php.net/manual/en/migration70.incompatible.php#migration70.incompatible.variable-handling.indirect) in handling indirect variables.
As we are no longer supporting PHP5, this can safely be added.
> Fix indirect variable handling in IPF form select (1.4.7)

- htdocs/libraries/icms/ipf/form/elements/Select.php
adding these brackets stops modules from bombing out saying that the function name should be a string. This is due to a [backward-incompatible change in PHP 7](https://www.php.net/manual/en/migration70.incompatible.php#migration70.incompatible.variable-handling.indirect) in handling indirect variables - ouch, we missed that one for a long time :-(
> fix indirect variable handling in IPF select form element

- .codeclimate.yml
Copied the configuration file from the TNG branch and updated some of the paths Resolves #1560
> Adding codeclimate configuration

- htdocs/modules/system/include/update.php
This will remove the openid and user_viewoid columns from the users table during an upgrade from pre-2.0 releases.
> Remove old columns from the users table Resolves #1561

- htdocs/modules/system/include/update.php
The method for dropping tables expects an array of columns. If there are none, there is a fatal error. Resolves #1589 
I had also done some minor changes to declaring some arrays and reused some code to reduce lines.
> handle if columns to remove from users table have already been removed

- htdocs/include/notification_select.php
- htdocs/include/notification_update.php
- htdocs/include/rating.rate.php
- htdocs/libraries/icms/core/Logger.php
- htdocs/libraries/icms/data/notification/Handler.php
- htdocs/libraries/icms/file/MediaUploadHandler.php
- htdocs/libraries/icms/form/elements/Dhtmltextarea.php
- htdocs/libraries/icms/view/Tpl.php
- htdocs/libraries/icms/view/theme/Object.php
- htdocs/modules/system/blocks/system_blocks.php
Regression testing uncovered several core elements that needed adjustment after the change in the global for $icmsModule. This converts the remaining variable references and resolves #1593
> Convert to current global for $icmsModule

- docs/changelog.md
- htdocs/include/version.php
- htdocs/modules/system/icms_version.php
- release_notes.md
This might be he last beta for 2.0.0, if no new regressions or bugs show up.
> Prepare 2.0.0 Beta 3

- htdocs/editors/CKeditor/ckeditor/config.js
This adds back the custom toolbars based on the user's groups. The plugins are from the original inclusion of FCKeditor and may need to be adjusted for what is in this release. The build-config.js had the plugins being used.
> Ckeditor custom config

- htdocs/install/class/IcmsInstallWizard.php
This resolves the deprecated dynamic properties error during installation
fixes #1603
> fix:add array declarations to installer 

- htdocs/install/common.inc.php
it is always there since 5.2.7, so this check can be removed.
> chore:no need to check for PHP_VERSION_ID anymore

- htdocs/libraries/icms/form/Element.php
- htdocs/libraries/icms/form/elements/Button.php
- htdocs/libraries/icms/form/elements/Checkbox.php
- htdocs/libraries/icms/form/elements/Password.php
- htdocs/libraries/icms/form/elements/Text.php
- htdocs/modules/system/icms_version.php
- htdocs/modules/system/templates/icms_form_elements_button_display.html
- htdocs/modules/system/templates/icms_form_elements_checkbox_display.html
- htdocs/modules/system/templates/icms_form_elements_password_display.html
- htdocs/modules/system/templates/icms_form_elements_text_display.html
CSS frameworks (Bulma, Bootstrap, Tailwind, ...) and almost every theme out there need specific HTML markup for their form solution to work well. The HTML implementation in the core was not flexible enough to allow that. I started with a button, and will gradually transform all hardcoded HTML in the core to using templates. 
I've started with these 4:
* Text Area
* Password
* Button
* Checkbox
Other parts will come in other PRs 
Smarty is included in the core specifically for this kind of functionality, so let's not re-invent the wheel. 
Added benefit : by using Smarty we should also have template caching, for that extra micro-second of speed :-)
> Templated form elements
