- htdocs/header.php
- htdocs/libraries/icms/view/theme/Object.php
> update Google Analytics to use the universal version

- htdocs/include/version.php
- htdocs/install/modules/protector/trust_path/modules/protector/include/postcheck_functions.php
- htdocs/libraries/icms/core/HTMLFilter.php
- htdocs/libraries/icms/ipf/permission/Handler.php
- htdocs/libraries/icms/view/block/Object.php
- htdocs/modules/system/icms_version.php
Some PHP fixes that I'm doing while configuring the beta site for impresscms.org. also, defining the new version 1.3.9
> Branches/impresscms 1.3

- License.txt
- README.md
I just created ReadMe for GitHub... Maybe this could help more people to find ImpressCMS ;)
See https://github.com/MekDrop/impresscms/tree/Adding-README for live demo ;)
Most parts of this readme were copied and pasted from our main site.
> Adding readme

- htdocs/modules/system/class/Adsense.php
- htdocs/modules/system/class/AdsenseHandler.php
- htdocs/modules/system/class/Autotasks.php
- htdocs/modules/system/class/AutotasksHandler.php
- htdocs/modules/system/class/AvatarsHandler.php
- htdocs/modules/system/class/Blocks.php
- htdocs/modules/system/class/BlocksHandler.php
- htdocs/modules/system/class/CommentsHandler.php
- htdocs/modules/system/class/Customtag.php
- htdocs/modules/system/class/CustomtagHandler.php
- htdocs/modules/system/class/GroupsHandler.php
- htdocs/modules/system/class/ImagesHandler.php
- htdocs/modules/system/class/Mimetype.php
- htdocs/modules/system/class/MimetypeHandler.php
- htdocs/modules/system/class/ModulesHandler.php
- htdocs/modules/system/class/Pages.php
- htdocs/modules/system/class/PagesHandler.php
- htdocs/modules/system/class/Positions.php
- htdocs/modules/system/class/PositionsHandler.php
- htdocs/modules/system/class/Rating.php
- htdocs/modules/system/class/RatingHandler.php
- htdocs/modules/system/class/SmiliesHandler.php
- htdocs/modules/system/class/Tags.php
- htdocs/modules/system/class/TagsHandler.php
- htdocs/modules/system/class/TplsetsHandler.php
- htdocs/modules/system/class/Userrank.php
- htdocs/modules/system/class/UserrankHandler.php
- htdocs/modules/system/class/UsersHandler.php
For ticket #886 
This just adds @property lines for documentation generation and better auto-completion support. Also it removes some duplicated other lines with @ from class description
> Added virtual properties for system module objects

- .travis.yml
> Php unit tests in travis

- .editorconfig
> Adding editorconfig Test #888

- htdocs/libraries/icms/core/Logger.php
For #906
Maybe not very beautiful looks but it works!
Template will be added once #23 will be verified and merged.
> Added some basic Exception handling

- htdocs/libraries/icms/view/theme/Factory.php
Some autofixes are still here but only for theme factory file. I hope this will be good enough ;)
> #911 selecting new theme causes index.php main page to go blank

- htdocs/libraries/icms/ipf/form/Base.php
- htdocs/libraries/icms/plugins/EditorHandler.php
> Editors caching bug fix

- htdocs/libraries/icms/core/Versionchecker.php
Some type definitions changed in  VersionCheckerTest.php
> #900 Make changes to pass VersionCheckerTest.php test

- htdocs/libraries/icms/ipf/Object.php
Changed test to empty instead of isset in updateMetas
- input values are always set
Clarified some comments and formatting
Fix #892
> IPF meta fields created on save #892

- htdocs/modules/system/templates/system_userinfo.html
> Add IDs to system_userinfo.html file

- htdocs/composer.json
- htdocs/libraries/icms/core/HTMLFilter.php
Use HTMLPurifier managed with Composer. Updating a new version of HTMLPurifier becomes as easy as 'composer update'
> HTMLPurifier using Composer

- htdocs/modules/system/templates/admin/images/system_popup_imagemanager_cloneimg.html
- htdocs/modules/system/templates/admin/images/system_popup_imagemanager_editimg.html
Clone and edit forms on the user side directed to bad URLs
test #919
> Corrected form target for some of the image manager actions

- htdocs/modules/system/admin/adsense/main.php
> It is now possible to override the adsenses template in the ACP.

- htdocs/modules/system/language/english/admin/adsense.php
> Correct link to the documentation page on the wiki now see #930

- docs/changelog.txt
- htdocs/include/functions.php
- htdocs/include/rating.rate.php
- htdocs/libraries/icms.php
- htdocs/libraries/icms/core/HTMLFilter.php
- htdocs/libraries/icms/view/Printerfriendly.php
- htdocs/libraries/icms/view/block/Object.php
- htdocs/libraries/icms/view/theme/Object.php
- htdocs/libraries/image-editor/image-edit.php
- htdocs/libraries/image-editor/plugins/crop/crop_image.php
- htdocs/libraries/image-editor/plugins/filter/filter_image.php
- htdocs/libraries/image-editor/plugins/resize/resize_image.php
- htdocs/modules/system/admin/images.php
This merges in several fixes resolved in the 1.3.9 and upcoming 1.3.10 releases. Some of the files show all lines being changed - that's because the line endings were automatically updated to Unix line endings.
> Update retro with 1.3.9/1.3.10 fixes

- htdocs/libraries/icms/view/theme/Object.php
removing extra quote, this should make the analytics work as expected. Test #929
> removing extra quote, this should make the analytics work as expected. Test #929

- htdocs/libraries/icms/ipf/Handler.php
- htdocs/libraries/icms/properties/Handler.php
Fixed that bug + few optimizations and comments
> Fix bug with assigning properties for objects

- htdocs/install/language/english/install.php
- htdocs/install/language/english/welcome.php
- htdocs/install/language/english/welcome_webmaster.tpl
- htdocs/install/makedata.php
- htdocs/libraries/icms/member/user/Object.php
Some more commits to finalise the 1.3.11 release, which I would like to finish by the end of the week.
> Preparation for 1.3.11

- htdocs/modules/system/admin/tplsets.php
In PHP 7.0 and later switch can't have multiple default sections
> Fixed empty page bug in tplsets admin for > PHP 7.0

- htdocs/libraries/icms/form/elements/Editor.php
- htdocs/libraries/icms/form/elements/Hiddentoken.php
Fixes some constructors for forms in 1.3.11 version
> Deprecated constructors for form elements fixes (1.3.11)

- htdocs/libraries/icms/response/HTML.php
> Fix for (((admin header logo not available for the theme templates)))

- htdocs/install/makedata.php
> Fix upgrade on first system access

- htdocs/include/constants.php
With #130 we removed tcpdf from repo but we have forgot to remove two constants...
> removed tcpdf path constants

- htdocs/composer.json
[prefer-stable](https://getcomposer.org/doc/04-schema.md#prefer-stable) is composer option that says composer that try to use stable packages first, otherwise look for anything other.
> Prefer stable option in composer.json

- .scrutinizer.yml
Enabled newer faster scrutinizer engine and some paths improvements (some removed because some paths moved to composer).
> Scrutinizer.yml improvements

- htdocs/editors/CKeditor/ceditfinder/_config.php
- htdocs/editors/CKeditor/formCkeditor.php
- htdocs/editors/CKeditor/xoops_version.php
- htdocs/include/autotasks.php
- htdocs/install/common.inc.php
- htdocs/libraries/icms.php
- htdocs/libraries/icms/Autoloader.php
- htdocs/libraries/icms/form/elements/captcha/Object.php
- htdocs/libraries/phpopenid/occommon.php
- htdocs/modules/system/admin.php
- htdocs/modules/system/admin/admin_header.php
- htdocs/modules/system/admin/groupperm.php
- htdocs/modules/system/icms_version.php
- htdocs/modules/system/include/common.php
- htdocs/plugins/sourceeditors/editarea/editor/edit_area_compressor.php
- htdocs/plugins/sourceeditors/editarea/xoops_version.php
- htdocs/plugins/textsanitizer/hashtags/hashtags.php
- htdocs/plugins/textsanitizer/hiddencontent/hiddencontent.php
- htdocs/plugins/textsanitizer/mentions/mentions.php
- htdocs/plugins/textsanitizer/syntaxhighlightcss/syntaxhighlightcss.php
- htdocs/plugins/textsanitizer/syntaxhighlighthtml/syntaxhighlighthtml.php
- htdocs/plugins/textsanitizer/syntaxhighlightjs/syntaxhighlightjs.php
- htdocs/plugins/textsanitizer/syntaxhighlightphp/syntaxhighlightphp.php
- htdocs/plugins/textsanitizer/wiki/wiki.php
- htdocs/plugins/textsanitizer/wmp/wmp.php
- htdocs/plugins/textsanitizer/youtube/youtube.php
Long time ago we needed to use `dirname(__FILE__)` but I think from PHP 5.3 (or maybe even earlier) we can use `__DIR__` constant for same thing.
> Replaces `dirname(__FILE__)` with `__DIR__`

- htdocs/.htaccess
- htdocs/index.php
> Fixed bug if icms is installed in subfolder

- htdocs/install/page_modcheck.php
Added simply check to installer to verify if urlrewriting is working on the server.
> installer now checks if url_rewriting works

- libraries/icms/response/HTML.php
Now in that case redirects to user.php
> Fixed: entering admin.php without login shows error that user is not defined

- include/site-closed.php
> Remove icms.css from site-closed.php (@todo improvement)

- composer.json
This will always optimize composer loader
> optimize-autoloader = true in composer

- libraries/geshi/geshi/index.html
- libraries/geshi/index.html
It seems two index.html files where left where previous was geshi library. This pull request remove these files.
> removed some index.html files from geshi libraries folder

- htdocs/.htaccess
Error found when trying help with ImpressCMS/Impresscms#266 issue
> Fixed: some Apache servers doesn't support 421 error code

- htdocs/index.php
> url rewriting for subfolders fix

- admin.php
Composer should handle that so I have removed upgrade check
> Remove if system module updated from admin.php

- core/providers/CacheServiceProvider.php
> fixed cache

- README.md
- docs/changelog.txt
- include/version.php
- modules/system/icms_version.php
> Prepare 2.0.0 alpha 7

- edituser.php
- finish_auth.php
- htdocs/editors/CKeditor/ceditfinder/_browse.php
- htdocs/editors/CKeditor/ceditfinder/lib/simpleimage.php
- htdocs/editors/tinymce/jscripts/plugins/icmsmlcontent/mlcontent.php
- htdocs/editors/tinymce/jscripts/plugins/xoopsimagemanager/xoopsimagebrowser.php
- include/comment_post.php
- include/functions.php
- libraries/icms.php
- libraries/icms/core/HTMLFilter.php
- libraries/icms/core/StopSpammer.php
- libraries/icms/db/legacy/PdoDatabase.php
- libraries/icms/image/category/Handler.php
- libraries/icms/ipf/Handler.php
- libraries/icms/member/user/Handler.php
- modules/system/admin/adsense.php
- modules/system/admin/autotasks.php
- modules/system/admin/modules.php
- modules/system/admin/preferences.php
- modules/system/admin/userrank.php
- plugins/sourceeditors/editarea/editor/edit_area_compressor.php
- user.php
- userinfo.php
@MekDrop requested this pull request.
It consists of patches automatically generated for this project on Scrutinizer:
https://scrutinizer-ci.com/g/ImpressCMS/impresscms/
> Scrutinizer Auto-Fixes

- libraries/icms/module/Handler.php
Fix the exception that causes the module loading to fail.
> Module page gives exception

- .travis.yml
ENV variables for travis moved to env section and removed PHP 5.6 testing.
> Smarter travis .env use

- htdocs/install/makedata.php
- htdocs/install/modulesadmin.php
- modules/system/admin/users/userform.php
Also check the administrator user's website, and HTML Purifier's base domain
and host domain
Fix #321
> Correct site constants - fixes admin logo link #321

- docs/changelog.txt
- htdocs/include/version.php
- htdocs/modules/system/icms_version.php
Prepare the release of 1.3.11 RC
> update version info in system module to 1.3.11

- htdocs/install/makedata.php
Regression in the installer due to #333 . Fix #355
> 355 - fix creation of initial user

- htdocs/libraries/icms/view/block/Object.php
correct signature for store and delete in icms_view_block_Object
Cleaning up the error messages in 1.3
> Strict PHP : correct signature

- .codeclimate.yml
- tests/configuration.xml
- tests/core/MainfileTest.php
some basic tests for checking if mainfile.php still works
> created mainfile.php test

- composer.json
some improvements to our composer file
> updating composer file options and info

- .whitesource
This should add whitesource security notifications
> Added whitesource integration support

- README.md
This partly solves issue #105 (other steps already has been made)
> renamed branches in readme: retro -> master

- htdocs/libraries/icms/member/groupperm/Handler.php
Reverts ImpressCMS/impresscms#367
> Revert "Update Group permission Handler.php for strict PHP"

- .restyled.yaml
Do not use restylizer plugin for 1.3.x branch
> no restylizer for 1.3.x branch

- .gitignore
- Homestead.yaml
- admin.php
- composer.json
- composer.lock
- core/providers/ModuleServiceProvider.php
- htdocs/index.php
- htdocs/install/common.inc.php
- htdocs/install/makedata.php
- htdocs/install/page_modulesinstall.php
- include/common.php
- include/constants.php
- include/cp_functions.php
- include/cp_header.php
- include/functions.php
- libraries/icms.php
- libraries/icms/ipf/Handler.php
- libraries/icms/view/block/Handler.php
- mainfile.php
- modules/system/admin/modules/modules.php
- modules/system/admin/preferences.php
- modules/system/autotask.php
- user.php
I did these changes without testing. Later today I will check if everything ok. For now this is just a possible pull request and possible solution.
> This probably will fix #295 issue

- htdocs/libraries/icms/core/Object.php
as mentioned by Tac: https://www.impresscms.org/modules/iforum/viewtopic.php?topic_id=5874&forum=43
> required missing is blocking error

- htdocs/include/version.php
- htdocs/modules/system/icms_version.php
- release_notes.txt
making version adjustments in order to release 1.4 alpha 2
> prepare 1.4 alpha 2

- htdocs/install/language/english/install.php
- htdocs/install/language/francais/install.php
- htdocs/install/language/italiano/install.php
update requirements text to 5.6, added recommendation for 7.2
the test is already to 5.6
fix #494
> Update php requirements to 5.6

- htdocs/install/class/mainfilemanager.php
- htdocs/install/class/settingmanager.php
- htdocs/install/class/textsanitizer.php
- htdocs/libraries/icms/form/Base.php
re-do of my previous PR, where I cherrypick changes from Mamba7x's PR, to avoid taking over the code style changes.
> PHP7 improvements based on mamba7x PR

- modules/system/admin/images.php
removed ref signs where they are not needed in  modules/system/admin/images/images.php
> Removed get results by reference where is not needed in modules/system/admin/images/images.php (2.0)

- composer.lock
- libraries/icms/member/user/Object.php
Fixes #113. 
Very simple fix - starting url without protocol, same protocol will be used as for main page.
> Fixes gravatar http for https bug

- composer.json
Added support section in composer.json with some links that could be useful easier finding where some ImpressCMS places are located.
> Added support section into composer.json

- htdocs/install/page_modcheck.php
> curl extension in installer now is requirement not optional

- .travis.yml
- composer.json
- composer.lock
- include/constants.php
It seems never version of codeclimate test reporter with few tweaks works fine :)
Good thing - it doesn't require special dev requirement in composer.json.
> Use newer CodeClimate test reporter

- composer.json
Composer.json can have 'keywords' section that is used in packagist as tags. I added at least few tags to make it possible to find icms easier :)
> added keywords section to composer.json

- composer.json
Another composer.json field filled.
> Added homepage to composer.json

- htdocs/modules/system/include/update.php
> Remove admin template folder in system module on upgrade

- finish_auth.php
- htdocs/editors/tinymce/jscripts/plugins/xoopsimagemanager/xoopsimagebrowser.php
- libraries/icms/auth/stores/local.php
- libraries/icms/form/elements/captcha/Object.php
- libraries/icms/form/elements/select/Image.php
- modules/system/admin/comments/admin_header.php
- modules/system/admin/modules/modules.php
- modules/system/admin/users/userform.php
- modules/system/blocks/system_admin_blocks.php
- modules/system/blocks/system_blocks.php
- register.php
- search.php
- user.php
- userinfo.php
We have some places with XOOPS_GROUPS_* constants. This pull request renames all these constants into ICMS_GROUPS_*.
> Fixes all places where was XOOPS_GROUP_* constants left

- libraries/icms/ipf/Controller.php
It seems $impresscms variable doesn't exit. This fix will fix in IPF controller how to get urls.
> Fixes getting url in controller component

- htdocs/install/install_tpl.php
- htdocs/install/page_dbsettings.php
- htdocs/install/prototype.js
Same thing that I found when I was changing installer to make work it with Aura.SQL for #527 pull request.
Because of missing [prototype.js](http://prototypejs.org) in installer user can't select collation for database based on selected encoding. So, missing JS added.
> Fixed installer collation selection

- htdocs/include/version.php
- htdocs/modules/system/icms_version.php
- release_notes.md
preparation of the 1.4 RC release
> Prepare 1.4 RC release

- libraries/icms/view/block/Object.php
Fixed #463 and #459 or at least improves these areas to close these two tickets :)
> Fixes 'improve with IPF' and 'We use this function only for visiblein code. We should find a better way to dea...' todo tickets

- .github/release-drafter.yml
- .github/workflows/release-drafter.yml
Builds but for unknown reason for me ignores if I set push also current branch but at least for 1.4 this should work fine :)
> Fixes release drafter

- .github/workflows/stale.yml
> Increase stale GitHub action run period to every 6 months

- htdocs/libraries/icms/core/Debug.php
- htdocs/modules/system/templates/system_adm_imagemanager_imglist.html
The main template was still referencing the old locations for included
templates
> Correct reference to imagemanager admin templates fix #590

- libraries/icms/view/Tpl.php
It seems after migrating to smarty 3 small bug was left in code. This will fix that.
> Fixed bug in smarty template touch function

- include/functions.php
Similar to #520 but for icms_getModuleHandler function.
> icms_getModuleHandler use container functionality

- htdocs/libraries/icms/module/Handler.php
As mentioned by ripstech in their blog: https://blog.ripstech.com/2020/sql-injection-impresscms/
> quoting the dirname as security improvement

- libraries/icms/ipf/Object.php
- modules/system/admin/autotasks.php
- modules/system/class/Autotasks.php
Previously in that case plain textfield was visible. From now source editor view is possible.
> When property is string with highlighting field correct control will be selected

- docs/changelog.txt
- htdocs/include/version.php
- htdocs/libraries/icms/module/Handler.php
- htdocs/modules/system/icms_version.php
- release_notes.txt
preparing the release of 1.3.12
> Prepare 1.3.12 security release

- modules/system/class/Autotasks.php
This will correctly detect if autotask code has some errors, and if yes log about that but doesn't rise 500 error like was possible before.
> Improved bad code handling in autotasks

- htdocs/install/page_siteinit.php
error in PHP 7.4 by checking if the variable is is set or not first
> Fix the "Trying to access array offset on value of type null" 

- htdocs/modules/system/admin/adsense/class/adsense.php
- htdocs/modules/system/admin/customtag/class/customtag.php
This probably should fix #659
However this doesn't fix weird behavior with HTML Purifier. Data is saved but not displayed again in forms. I'm not sure if there is a away around it without doing big changes.
> This probably should fix #659

- modules/system/templates/system_userform.html
So email can be used comfortably as a username
> Making input boxes accept wider text strings

- modules/system/admin/images/browser.php
It seems never PHP has issue when switch has multiple defaults. This should fix that.
> Fixed image browse multiple default for switch

- htdocs/themes/core/modules/system/admin/groups/system_adm_groups.html
- modules/system/templates/admin/groups/system_adm_groups.html
It seems after migrating to Smarty 3 few errors in admin groups templates where left. This should fix them.
> Fixed smarty errors for groups admin page

- docs/changelog.txt
- htdocs/include/version.php
- htdocs/modules/system/icms_version.php
making the version adjustments for the release of 1.4.1 final
> prepare release 1.4.1 final

- modules/system/admin/tplsets.php
This should fix tplsets in admin downloading and cloning
> Fixed downloading and cloning in admin tplsets

- composer.json
- core/Providers/SessionServiceProvider.php
- libraries/icms/ipf/Handler.php
This should fix bug when admin randomly was redirected to index.php because incorrect session cookie paths
> Fixes session cookies path for modules

- .github/workflows/test.yml
I think composer files changes should be tested too! So, this pull request adds such tests.
> Run CI tests also for composer.json and composer.lock file changes

- composer.json
- composer.lock
- include/pdf.php
- language/english/global.php
[tecnickcom/tcpdf](https://github.com/tecnickcom/TCPDF) requires GPL 3.0 license but we use GPL 2.0 only. So I switch PDF rendering with [dompdf/dompdf](https://github.com/dompdf/dompdf). I hope this will be enough to solve this issue.
> Replace tecnickcom/tcpdf with dompdf/dompdf due license incompatibility

- .github/workflows/test.yml
This will run all tests with PHP 8.0 too
> Added PHP 8.0 for tests

- core/SetupSteps/Module/Install/CacheClearSetupStep.php
- core/SetupSteps/Module/Uninstall/CacheClearSetupStep.php
- core/SetupSteps/Module/Update/CacheClearSetupStep.php
the 'extensions' level was missing
> correct the interface path for the setupsteps

- core/Models/OnlineHandler.php
> Fixed #767: logging into admin gives db error

- composer.lock
- core/Controllers/LegacyController.php
- core/Extensions/ComposerDefinitions/RoutesComposerDefinition.php
- include/constants.php
(as title says)
To make this work - clear cache first.
> Fixed bug when ImpresCMS was installed in subfolder and route grouping functionality prevendted to add correct prefixes

- core/Extensions/Editors/EditorsRegistry.php
- core/View/Form/Elements/Captcha/Image.php
- core/View/Form/Elements/Captcha/ImageMode.php
- core/View/Form/Elements/Captcha/ImageRenderer.php
- core/View/Form/Elements/Captcha/TextMode.php
- core/View/Form/Elements/Captcha/config.php
- core/View/PageBuilder.php
- core/View/Theme/ThemeComponent.php
- core/View/Theme/ThemeFactory.php
- include/findusers.php
- include/site-closed.php
- plugins/smarty/compiler.foreachq.php
- plugins/smarty/compiler.includeq.php
- plugins/smarty/compiler.xoAppUrl.php
- plugins/smarty/compiler.xoImgUrl.php
- plugins/smarty/resource.db.php
- plugins/sourceeditors/codemirror/codemirror.php
- plugins/sourceeditors/editarea/editarea.php
- plugins/sourceeditors/editarea/language/english.php
It seems license URL in many our PHP files pointed to incorrect location. Updated.
> Fixed URLs for GPLv2 license in php files

- SECURITY.md
This will add file that should be displayed in Security tab of repository.
> Added  'Security Policy' file

- SECURITY.md
As Hackerone is not yet a public project, nobody can access it yet. Pointing to the form then
> change link to Hackerone to the security form

- include/version.php
- modules/system/icms_version.php
Prepare for the 2.0a10 release
> Prepare for the 2.0a10 release

- core/Logger.php
- htdocs/install/class/xoopsinstallwizard.php
https://www.php.net/manual/en/migration74.deprecated.php#migration74.deprecated.core.array-string-access-curly-brace
> Fixes deprecation 'Array and string offset access using curly braces'

- htdocs/libraries/icms/core/Password.php
> more strict comparison of variables

- htdocs/install/common.inc.php
Fixed HackerOne#1050071 issue reported by hackerone_success
https://hackerone.com/bugs?subject=impresscms&report_id=1050071&view=new&substates%5B%5D=new&reported_to_team=&text_query=&program_states%5B%5D=2&program_states%5B%5D=3&program_states%5B%5D=4&program_states%5B%5D=5&sort_type=latest_activity&sort_direction=descending&limit=25&page=1
> Fixed possible file system exposing due language cookie on installer (reported by hackerone_success)

- htdocs/install/class/xoopsinstallwizard.php
> Fixed possible file system exposing due language cookie on installer (reported by hackerone_success) 

- core/ModelController.php
Similar as #812 but for ImpressCMS 2.0
> Prevents using submitted filenames with ../ for modelcontroller

- core/Models/BlockHandler.php
Simple compatibility fix for newer PHP versions
> Fixed short if bug for newer PHP in BlockHandler

- .whitesource
> Remove whitesource config

- htdocs/libraries/icms/ipf/view/Table.php
put into place getcookie() and setcookie() to clean up the way the filtering is stored in functional cookies
> Fix the amount of cookies

- core/View/Table/Table.php
> Fixed bug with too long cookie names for Table component

- htdocs/include/functions.php
- htdocs/install/class/settingmanager.php
- htdocs/invite.php
- htdocs/misc.php
Removing many no longer used and clearly mentioned functionalities that are deprecated since 1.3.x
> Cleanup deprecated functions in functions.php

- core/Extensions/Smarty/Compiler/IncludeqCompiler.php
So some themes wouldn't show page or blocks contents
> Fixed includeq not working in smarty anymore bug

- htdocs/footer.php
- htdocs/include/cp_functions.php
- htdocs/include/functions.php
Anti-clickjacking measure by adding a header("X-Frame-Options: SAMEORIGIN"); header directive
> anti-clickjacking

- htdocs/include/common.php
- htdocs/include/functions.php
- htdocs/install/class/dbmanager.php
- htdocs/install/class/textsanitizer.php
- htdocs/install/common.inc.php
Here was few small issues fixed that are visible when installing in newer PHP
> Fixed some warnings and notices in installer for newer PHP versions

- htdocs/misc.php
> Smiles in misc.php now are escaped

- htdocs/include/registerform.php
This will be fixed with after this pull request
> Fixed syntax error in include/registerform.php

- htdocs/plugins/preloads/autologin.php
close #912
A very small change, but worth it :-)
> fix vulnerability in autoloader

- htdocs/libraries/image-editor/image-edit.php
> block path traversal in image editor, transform .. to _

- README.md
Adding composer installation instructions to the readme file
> add install instructions to readme for 2.0

- htdocs/libraries/icms/ipf/view/Table.php
- htdocs/register.php
The input filtering was not taking into consideration the POST changes. Fixes #936
> Fixes/ipf table filtering - limitsel missing POST value

- htdocs/modules/system/templates/system_popup_imagemanager_imglist.html
The paths for additional templates needed to be updated for the relocation of the system submodule template. Fixes #603
> Adjusted template file inclusion for correct path. Fixes #603

- composer.json
based on a dependabot vulnerability report
> skip vulnerable versions of composer/composer

- composer.json
- composer.lock
Now this middleware can be updated to latest version with dependatbot
> Fixed tuupola/server-timing-middleware requirements

- composer.lock
Fixes issues with phpmailer/phpmailer and league/flysystem dependency issues.
> Fixed few security issues with packages

- footer.php
- header.php
> Fixed namespaces issues for never PHP in footer.php and header.php

- htdocs/include/findusers.php
- htdocs/libraries/icms/ipf/view/Table.php
- htdocs/themes/iTheme/theme_admin.html
> Added filtering to the input in setSortOrder in icms_ipf_table

- htdocs/install/page_modulesinstall.php
Fix bug when installer crashed when trying to upgrade system module
> Fixes system module upgrading from installer

- composer.json
This fixes some conflicting data.
> Remove few system module services that was previously defined in core

- htdocs/install/page_modulesinstall.php
> Fixes few issues with page_modulesinstall.php for installer

- core/Extensions/SetupSteps/Module/Install/BlockSetupStep.php
- core/Extensions/SetupSteps/Module/Update/BlocksSetupStep.php
- core/Models/BlockHandler.php
Previously for all blocks that were created from modules, constants for titles weren't correctly resolved. This will fix that.
> Fixed module block titles/names from constants resolving

- core/View/PageNav.php
After this it will be possible to navigate between pages again.
> Fixed incorrect urls for PageNav generated links

- htdocs/libraries/icms/core/DataFilter.php
This takes care of places where not second parameter is defined for addSlashes (like the login - oops)
> Add a default parameter to addSlashes

- htdocs/editors/CKeditor/formCkeditor.php
- htdocs/editors/CKeditor/imagebrowser.php
- htdocs/editors/CKeditor/language/english.php
- htdocs/editors/CKeditor/language/index.html
When enabling and selecting editors in General Preferences, CKeditor is showing the language constant rather than the display text.
> Undefined language constants for CKeditor in general preferences

- htdocs/user.php
Ensuring the username obtained from the cookie is only text.
> User cookie could be contaminated - filter added

- htdocs/install/modules/protector/trust_path/modules/protector/admin/index.php
- htdocs/install/modules/protector/trust_path/modules/protector/class/protector.php
Removed full path display in the ACP and improved filtering of user input
> Protector enhancements and added security

- .github/workflows/test.yml
- composer.json
> Fix GitHub CI Tests + composer.json

- htdocs/install/modules/protector/trust_path/modules/protector/class/protector.php
> Changing filter method for request_uri to filter_sanitize_string

- core/View/Template.php
It seems we have left few bugs for smarty 4 plugins when they were registered. This will fix that.
> Fixed plugins registration for Smarty 4

- core/Message.php
- core/Response/ConfirmationResponse.php
Rewritten confirmation as PSR response
> Confirmation now is possible to do from controllers

- htdocs/libraries/icms/core/DataFilter.php
- htdocs/libraries/icms/ipf/view/Table.php
- htdocs/modules/system/admin/avatars/main.php
- htdocs/modules/system/admin/groups/main.php
- htdocs/modules/system/admin/mailusers/mailform.php
- htdocs/modules/system/admin/mailusers/main.php
- htdocs/modules/system/admin/modulesadmin/main.php
- htdocs/modules/system/admin/pages/main.php
- htdocs/modules/system/admin/preferences/main.php
Making sure we apply the proper filters to inner elements of arrays and validating sessions before processing POST requests
> Additional input filtering - mailusers, findusers, checkVarArray inner elements

- docs/changelog.md
- htdocs/include/version.php
- htdocs/modules/system/icms_version.php
update version numbers in preparation of the release of ImpressCMS 1.4.4
> Prepare 1.4.4

- .github/release-drafter.yml
- .github/workflows/apigen.yml
- README.md
This will return/make some stuff to work after branches renaming
> Updated branch references & readme

- composer.json
- composer.lock
> Upgrade dompdf to 2.0.0

- bin/console
- composer.lock
It seems there was a bug that sometimes a container can't be resolved in commands. This should fix that.
> Fix console container bug

- migrations/20200806214630_remove_settings_to_make_possible_to_use_old_style_d_h_t_m_l_editor.php
Previously migrations for this case failed.
> Fix migration bug when there are not yet any editor installed

- core/Providers/FilesystemServiceProvider.php
It seems without it now ICMS fails when displaying any page
> Revert filesystems $provides array

- composer.json
- composer.lock
It seems [true/punycode](https://github.com/true/php-punycode) is not needed anymore. So, removing.
> Remove 'true/punny'

- composer.json
This helps us to run icms in docker container
> Turn off composer autooptimizations

- htdocs/include/version.php
- htdocs/modules/system/admin/mailusers/main.php
- htdocs/modules/system/icms_version.php
> Fix mailuser

- core/Commands/ModuleUpdateCommand.php
This will fix some translation issues for some modules when trying to install from CLI.
> Module update CLI command now tries to load module related 'common' and 'modinfo' language files

- core/Extensions/ExtensionDescriber/ArrayAccessTrait.php
- core/Extensions/ExtensionDescriber/DescribedItemInfoInterface.php
- core/Extensions/ExtensionDescriber/ExtensionDescriberInterface.php
- core/Extensions/ExtensionDescriber/Module/ImpressCMSComposerModuleDescriber.php
- core/Extensions/ExtensionDescriber/Module/ImpressCMSVersionModuleDescriber.php
- core/Extensions/ExtensionDescriber/ModuleInfo.php
- core/Extensions/ExtensionDescriber/Theme/ImpressCMSComposerThemeDescriber.php
- core/Extensions/ExtensionDescriber/Theme/ImpressCMSLegacyThemeDescriber.php
- core/Extensions/ExtensionDescriber/ThemeInfo.php
- core/Models/Module.php
- core/Models/ModuleHandler.php
- core/View/Theme/ThemeFactory.php
Adds some structure for theme and modules descriptions and the possibility to better know what descriptions what things have.
> Theme and Module info now as Objects

- docs/language_changelog.txt
- language/english/addons.php
Moved some language strings from the system module to separate the namespace in the core. Related to ImpressCMS/system-module#12
> Added new addons translation namespace

- core/Extensions/SetupSteps/Module/Update/BlocksSetupStep.php
- core/Models/User.php
Maybe there is a better way but I think for now it would at least not crash when updating a module with blocks.
Resolves #1226
> Prevents crash when updating module from command line

- htdocs/install/page_dbsettings.php
> Fix: notice undefined index  utf8 in htdocs/install/page_dbsettings.php on line 138

- htdocs/include/functions.php
- htdocs/install/class/textsanitizer.php
- htdocs/libraries/icms/core/DataFilter.php
- htdocs/libraries/icms/file/MediaUploadHandler.php
This is for making it compatible with newer PHP versions.
> Remove get_magic_quotes_gpc calls

- core/DataFilter.php
Like #1325 but for DataFilter
Resolves #1088
> addSlashes and stripSlashesGPC also deprecated in DataFilter

- composer.lock
- core/Extensions/SetupSteps/Module/Update/BlocksSetupStep.php
> Fixes syntax error in blocks setup step

- htdocs/modules/system/include/update-14.php
Moving previous upgrade to update-14.php and setting up new update for 1.5
> removing files from previous versions that are no longer there

- htdocs/libraries/icms/view/block/Handler.php
No longer available in PHP 8.0
> replace create_function with anonymous function

- composer.json
- composer.lock
> Upgrade impresscms/codemirror integration to 0.2.3

- .github/dependabot.yml
- composer.lock
For now more frequently updates are needed for composer packages.
> Dependabot composer updates switched into weekly

- composer.json
- composer.lock
This adds compatibility with PHP 8.1
> Upgrade middlewares/aura session to 2.x

- composer.json
- composer.lock
This adds PHP 8.1 compatibility
> Upgraded cerdic/css-tidy to 2.0.3

- composer.json
- composer.lock
- core/Data/BootConfig.php
- htdocs/install/common.inc.php
This adds support for PHP 8.2
And also impresscms/composer-addon-installer-plugin is upgraded to min v1.0.6.
> Upgrade vlucas/phpdotenv to 5.5.0

- htdocs/install/page_dbsettings.php
Fixed XSS via DB_CHARSET parameter while on installation.
Before:
Reported on https://hackerone.com/reports/1825770
After:
sanitized error with htmlentities
> Fix XSS via DB_CHARSET parameter (H1 #1825770)

- htdocs/install/makedata.php
It seems this enough for fix #1345
> Fixed #1345 - 'undefined constant in PHP 8 on install/page_tablesfill.php page'

- htdocs/modules/system/admin/preferences/main.php
> Fixed bug when saving system preference

- htdocs/libraries/icms/member/user/Handler.php
Fix #1090 
It seems the problem was not with MySQL 8 but with the query code that the builder updated and insert user queries. Not always there were enough parameters for previously used `sprintf`.
> Fixed #1090 - user creating and editing

- htdocs/install/language/nederlands/install.php
- htdocs/install/language/nederlands/install2.php
Adjusting some quotes in response to errors on Scrutinizer
> Errors in the Nederlands install language files

- htdocs/libraries/icms/core/DataFilter.php
- htdocs/libraries/icms/db/Connection.php
- htdocs/libraries/icms/db/mysql/Connection.php
- htdocs/libraries/icms/ipf/Object.php
- htdocs/libraries/icms/view/block/Handler.php
- htdocs/modules/system/admin/adsense/main.php
- htdocs/modules/system/admin/blocksadmin/class/blocksadmin.php
- htdocs/modules/system/admin/pages/class/pages.php
- htdocs/modules/system/blocks/system_admin_blocks.php
- htdocs/modules/system/blocks/system_blocks.php
The change in the adsense component was the only one that failed. The other changes addressed warnings. And there are some code style changes because of our style guide - automatically applies when I edit a file and save. Line endings are also changed
> PHP8 compliance updates

- htdocs/include/version.php
- htdocs/libraries/icms/view/theme/Object.php
- htdocs/plugins/preloads/googleanalytics.php
Quick update to integrate the patch that @skenow  posted on the forums.
> Release 1.4.5 - 1.4 with GA4 fix

- README.md
- docs/changelog.md
- htdocs/include/version.php
- htdocs/modules/system/icms_version.php
This release will serve to get a final release out there that works with GA4.
> Preparing 1.4.5 final

- htdocs/edituser.php
- htdocs/libraries/icms/core/DataFilter.php
- htdocs/userinfo.php
Close #1422 
Editing a profile was stripping tags from the user signature at the wrong time (after text input filter). The text input filter should also strip tags (it now does).
> Updates to DataFilter - string filters for PHP8 and signature filtering

- htdocs/libraries/icms/module/Object.php
#fix 1495 by checking if the returned value is an array, and if not, make an array out of it.
> bool to countable in module object

- htdocs/modules/system/blocks/system_blocks.php
This can then be used in the theme block
> Add current theme info into the theme block

- htdocs/language/francais/global.php
- htdocs/language/nederlands/global.php
Changed the _SHORTDATESTRING notation to dd-mm-yyyy instead of dd/mm/yyyy
> Date notation fixes for europe in Dutch translations

- docs/changelog.md
- htdocs/include/version.php
- htdocs/modules/system/icms_version.php
doing the paperwork to get the new version released.
> chore:Prepare 1.4.6 rc

- htdocs/language/english/user.php
- htdocs/language/francais/user.php
- htdocs/language/italiano/user.php
- htdocs/language/nederlands/user.php
- htdocs/language/schinese/user.php
- htdocs/lostpass.php
- htdocs/user.php
A separate PR for language constants discovered while addressing the password reset key. The non-English languages need review - I'm not fluent enough to be certain of the proper structure for adding the second variable to the constant
> Update language constants for users

- htdocs/modules/system/blocks/system_blocks.php
- htdocs/modules/system/icms_version.php
- htdocs/modules/system/language/english/blocks.php
- htdocs/modules/system/language/francais/blocks.php
- htdocs/modules/system/language/italiano/blocks.php
- htdocs/modules/system/language/nederlands/blocks.php
> Cleanup social provider list

- htdocs/modules/system/admin/blocksadmin/class/blocksadmin.php
> Remove data for bannerclient from install 

- htdocs/footer.php
- htdocs/header.php
- htdocs/include/cp_functions.php
- htdocs/libraries/icms/ipf/Metagen.php
Some more removals of the $icmsModule. The modules I tested work after this update.
> Third batch of $icmsModule removals

- README.md
- docs/changelog.md
- htdocs/include/version.php
- htdocs/modules/system/icms_version.php
the versioning of 2.0.0 beta 1 was a bit off, correcting that for the beta 2 release beforehand
> Update version.php to new 2.0.0 beta 2

- htdocs/content.php
- htdocs/footer.php
- htdocs/header.php
- htdocs/include/commentform.inc.php
- htdocs/include/cp_functions.php
- htdocs/include/functions.php
- htdocs/include/notification_update.php
- htdocs/modules/system/admin/images/browser.php
For some reason I forgot to PR the second part of the icmsmodule cleanup I did.
> Icmsmodule cleanup part2

- htdocs/libraries/icms/data/notification/Handler.php
> Remove use of $icmsModule in notification Handler.php

- htdocs/libraries/icms/core/Object.php
- htdocs/libraries/icms/db/mysql/Connection.php
2 bugs I encountered during testing for the content module.
> Small bug fixes

- htdocs/editors/CKeditor/imagebrowser.php
> Fix:Fix the CKEditor Image Manager that couldn't find WideImage

- .codeclimate.yml
Defining the rulesets for PHPMD to remove the controversial rules
> Choosing the rulesets for PHPMD in codeclimate see #1607

- htdocs/libraries/icms/ipf/view/Column.php
- htdocs/libraries/icms/ipf/view/Table.php
Also adapted their use in icms_ipf_view_Table, which is the only one using that class afaik.
A last fix before 2.0 Final
> fix: improve visibility of icms_ipf_view_column

- README.md
- docs/changelog.md
- htdocs/include/version.php
- htdocs/modules/system/icms_version.php
- release_notes.md
Changing the version information for the 2.0.1 release.
> Release 2.0.1

- htdocs/modules/system/include/update.php
This resulted in the question to upgrade the system module each time
> fix:in some cases, the update to version 48 was not persisted in the DB

- htdocs/libraries/icms/core/Object.php
> fix:remove duplicate code from icms_core_object

- htdocs/modules/system/icms_version.php
- htdocs/modules/system/include/update.php
adsense, autotasks, customtag, mimetype, rating are all fully IPF-compliant and can benefit from automatic updates.
> Adding automatic update of the system module

- README.md
- docs/changelog.md
- htdocs/include/version.php
- htdocs/modules/system/icms_version.php
Other
___
- Update version from RC to final release 2.0.2
- Increment build number and update status constants
- Update documentation and changelog for final release
- Consolidate changelog entries from beta and RC
___
```mermaid
flowchart LR
A["Version Files"] --> B["Update Status"]
B --> C["Final Release"]
D["Documentation"] --> E["Update Changelog"]
E --> C
F["README"] --> G["Remove RC Label"]
G --> C
```
<details> <summary><h3> File Walkthrough</h3></summary>
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>version.php</strong><dd><code>Update core version constants for final release</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> prepare-2.0.2
